apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-miuser004
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app-miuser004
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/ErikBussink/tanzu-java-web-app-miuser004
      ref:
        branch: main
